version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - test

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: go test ./...
